### ISSUE TITLE
[PE-D] User Guide instructs to use "Close Contact" but is different in the app as we are instructed to use "Close-Contact"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T12-1/tp#140] opened 2022-04-01 16:37 UTC
The app requests user to use "close-contact":
![App Close-Contact.png](https://raw.githubusercontent.com/joey-chance/ped/main/files/2fcfbdf8-e755-4980-bc43-eda3be2f7a23.png)

But the user guide requests user to use "close contact":
![User Guide Close Contact.png](https://raw.githubusercontent.com/joey-chance/ped/main/files/0136c593-bcdf-44bc-b5fd-c727d4afed0d.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: joey-chance/ped#4

**Comment by louisdavinlie** [comment] 2022-04-02 13:12
Duplicate of #123

**Closed as completed** 2022-04-02 13:15 UTC
Labels: duplicate
